// This file is autogenerated. Do not edit.
import .schema
import .meta.core
import .meta.applicator
import .meta.unevaluated
import .meta.validation
import .meta.meta-data
import .meta.format-annotation
import .meta.content
URL-MAPPING ::= {
  "https://json-schema.org/draft/2020-12/schema": SCHEMA,
  "https://json-schema.org/draft/2020-12/meta/core": CORE,
  "https://json-schema.org/draft/2020-12/meta/applicator": APPLICATOR,
  "https://json-schema.org/draft/2020-12/meta/unevaluated": UNEVALUATED,
  "https://json-schema.org/draft/2020-12/meta/validation": VALIDATION,
  "https://json-schema.org/draft/2020-12/meta/meta-data": META-DATA,
  "https://json-schema.org/draft/2020-12/meta/format-annotation": FORMAT-ANNOTATION,
  "https://json-schema.org/draft/2020-12/meta/content": CONTENT,
}
